model:
  params:
    n_estimators: 2 # Starting point
    random_state: 42
    max_depth: 12
    n_jobs: -1
    verbose: 1
    warm_start: True
  log:
    step: 1
    n_estimators: 20 # Best metric point

path:
  train: data/training_set_rel3.tsv
  test: data/test_set.tsv
  pred: data/predictions.csv
  save: autograde_essay/models/rf_model.pkl
  word2vec: autograde_essay/models/word2vecmodel.bin

repo: https://github.com/MaxAndreyko/autograde-essay/

preprocess:
  num_features: 300
  min_word_count: 40
  num_workers: 8
  context: 10
  downsampling: 0.001
