name: check_train
on:
    push:
      branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Setup Google Drive credentials
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.DVC_GDRIVE_SERVICE_ACC_CREDITS }}
        run: |
            echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > dvc-remote-connections.json
            dvc remote modify storage gdrive_service_account_json_file_path dvc-remote-connections.json
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install
        
      - name: Execute train script
        run: |
          source .venv/bin/activate
          python ./autograde_essay/train.py
      - name: Execute inference script
        run: |
          source .venv/bin/activate
          python ./autograde_essay/infer.py
